Correcciones para verificar si el ZIP con las dependencias está o no disponible

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -8,8 +8,8 @@ echo "  checking runtime"
 runtime=`"${R_HOME}/bin/Rscript" -e 'cat(R.version$os)'`
 architecture=`"${R_HOME}/bin/Rscript" -e 'cat(R.version$arch)'`
 
-echo "  found: '$runtime'"
-echo "   arch: '${architecture}'"
+echo "found: '$runtime'"
+echo "arch: '${architecture}'"
 
 redatamurl=""
 
@@ -27,27 +27,34 @@ fi;
 ##final version 1.0.1
 engine_file="libredengine-1.0.1-final"
 
-url="https://redatam-core.s3.us-west-2.amazonaws.com/core-dev/$redatamurl/redatamx-core-$redatamurl-1.0.1-final.zip"
+URL="https://redatam-core.s3.us-west-2.amazonaws.com/core-dev/$redatamurl/redatamx-core-$redatamurl-1.0.1-final.zip"
+DEST="redatam-engine.zip"
 
-echo "  using download from '$url'"
+echo "using download from '$URL'"
 
-echo "  checking REDATAM libraries"
+echo "checking REDATAM libraries"
 
 allok=yes
 
 mkdir -p inst/redengine
 
 if [ ! -e inst/redengine/$engine_file ]; then
-  echo "  cannot find current redatam runtime files"
-  echo "  attempting to download them"
-  echo "  download.file('$url','redatam-engine.zip',mode='wb')"|${R_HOME}/bin/R --vanilla --slave
-  echo "  unpacking current redatam runtime"
+  echo "cannot find current redatam runtime files"
+  echo "attempting to download them"
+  echo "download.file('$URL','$DEST',mode='wb')"|${R_HOME}/bin/R --vanilla --slave
 
-  unzip -o -d tmpredatam redatam-engine.zip
+  if [ -f $DEST ]; then
+    echo "unpacking current redatam runtime"
+    unzip -o -d tmpredatam redatam-engine.zip
 
-  cp tmpredatam/release/lib/$engine_file.* inst/redengine
-  rm -rf redatamx-engine.zip
-  rm -rf tmpredatam
+    cp tmpredatam/release/lib/$engine_file.* inst/redengine
+    rm -rf redatamx-engine.zip
+    rm -rf tmpredatam
+  else
+    echo "Can't download file '$URL', compilation compilation continue without runtime"
+    #exit 1
+  fi
+
 fi
 
 exit 0
